import type { Chapter, Subject } from "./types"

export async function getEnhancedChapterData(): Promise<Chapter[]> {
  // Simulating API call with enhanced data
  return [
    {
      id: "phy-math-1",
      subject: "Physics",
      chapter: "Mathematics in Physics",
      class: "Class 11",
      unit: "Mechanics 1",
      yearWiseQuestionCount: {
        "2019": 0,
        "2020": 2,
        "2021": 5,
        "2022": 5,
        "2023": 3,
        "2024": 7,
        "2025": 6,
      },
      questionSolved: 0,
      totalQuestions: 28,
      status: "Not Started",
      isWeakChapter: false,
      difficulty: "Easy",
      estimatedTime: 120,
      accuracy: 0,
      tags: ["vectors", "calculus", "trigonometry"],
      description:
        "Mathematical tools and techniques used in physics including vectors, calculus, and coordinate systems.",
      prerequisites: ["Basic Mathematics", "Trigonometry"],
      relatedChapters: ["phy-motion-1d", "phy-motion-2d"],
    },
    {
      id: "phy-units-1",
      subject: "Physics",
      chapter: "Units and Dimensions",
      class: "Class 11",
      unit: "Mechanics 1",
      yearWiseQuestionCount: {
        "2019": 2,
        "2020": 6,
        "2021": 8,
        "2022": 4,
        "2023": 6,
        "2024": 3,
        "2025": 10,
      },
      questionSolved: 39,
      totalQuestions: 39,
      status: "Completed",
      isWeakChapter: true,
      difficulty: "Easy",
      estimatedTime: 90,
      lastStudied: "2024-12-01T10:30:00Z",
      accuracy: 65,
      tags: ["SI units", "dimensional analysis", "measurement"],
      description: "Fundamental and derived units, dimensional analysis, and measurement techniques.",
      prerequisites: ["Basic Mathematics"],
      relatedChapters: ["phy-math-1"],
    },
    {
      id: "phy-motion-1d",
      subject: "Physics",
      chapter: "Motion In One Dimension",
      class: "Class 11",
      unit: "Mechanics 1",
      yearWiseQuestionCount: {
        "2019": 2,
        "2020": 10,
        "2021": 6,
        "2022": 7,
        "2023": 0,
        "2024": 2,
        "2025": 6,
      },
      questionSolved: 33,
      totalQuestions: 33,
      status: "Completed",
      isWeakChapter: true,
      difficulty: "Medium",
      estimatedTime: 180,
      lastStudied: "2024-11-28T14:15:00Z",
      accuracy: 72,
      tags: ["kinematics", "velocity", "acceleration", "graphs"],
      description:
        "Study of motion along a straight line including displacement, velocity, acceleration, and motion graphs.",
      prerequisites: ["Mathematics in Physics"],
      relatedChapters: ["phy-motion-2d", "phy-laws-motion"],
    },
    {
      id: "phy-motion-2d",
      subject: "Physics",
      chapter: "Motion In Two Dimensions",
      class: "Class 11",
      unit: "Mechanics 1",
      yearWiseQuestionCount: {
        "2019": 3,
        "2020": 10,
        "2021": 2,
        "2022": 7,
        "2023": 8,
        "2024": 0,
        "2025": 8,
      },
      questionSolved: 25,
      totalQuestions: 38,
      status: "In Progress",
      isWeakChapter: false,
      difficulty: "Medium",
      estimatedTime: 240,
      lastStudied: "2024-12-05T09:45:00Z",
      accuracy: 78,
      tags: ["projectile motion", "circular motion", "vectors"],
      description: "Motion in a plane including projectile motion, circular motion, and relative velocity.",
      prerequisites: ["Motion In One Dimension", "Mathematics in Physics"],
      relatedChapters: ["phy-motion-1d", "phy-laws-motion"],
    },
    {
      id: "phy-laws-motion",
      subject: "Physics",
      chapter: "Laws of Motion",
      class: "Class 11",
      unit: "Mechanics 1",
      yearWiseQuestionCount: {
        "2019": 3,
        "2020": 0,
        "2021": 6,
        "2022": 5,
        "2023": 8,
        "2024": 6,
        "2025": 8,
      },
      questionSolved: 36,
      totalQuestions: 36,
      status: "Completed",
      isWeakChapter: false,
      difficulty: "Hard",
      estimatedTime: 300,
      lastStudied: "2024-11-30T16:20:00Z",
      accuracy: 85,
      tags: ["Newton's laws", "friction", "tension", "equilibrium"],
      description: "Newton's three laws of motion, friction, tension in strings, and equilibrium of particles.",
      prerequisites: ["Motion In One Dimension", "Motion In Two Dimensions"],
      relatedChapters: ["phy-work-energy", "phy-momentum"],
    },
    {
      id: "phy-work-energy",
      subject: "Physics",
      chapter: "Work Power Energy",
      class: "Class 11",
      unit: "Mechanics 1",
      yearWiseQuestionCount: {
        "2019": 10,
        "2020": 4,
        "2021": 9,
        "2022": 10,
        "2023": 2,
        "2024": 7,
        "2025": 5,
      },
      questionSolved: 0,
      totalQuestions: 47,
      status: "Not Started",
      isWeakChapter: true,
      difficulty: "Hard",
      estimatedTime: 360,
      accuracy: 0,
      tags: ["work", "energy", "power", "conservation"],
      description: "Work-energy theorem, kinetic and potential energy, power, and conservation of energy.",
      prerequisites: ["Laws of Motion"],
      relatedChapters: ["phy-momentum", "phy-rotation"],
    },
    {
      id: "phy-momentum",
      subject: "Physics",
      chapter: "Center of Mass Momentum and Collision",
      class: "Class 11",
      unit: "Mechanics 1",
      yearWiseQuestionCount: {
        "2019": 7,
        "2020": 5,
        "2021": 2,
        "2022": 7,
        "2023": 6,
        "2024": 10,
        "2025": 0,
      },
      questionSolved: 0,
      totalQuestions: 37,
      status: "Not Started",
      isWeakChapter: true,
      difficulty: "Hard",
      estimatedTime: 300,
      accuracy: 0,
      tags: ["momentum", "collision", "center of mass", "impulse"],
      description: "Linear momentum, impulse, collisions, and center of mass of systems.",
      prerequisites: ["Laws of Motion"],
      relatedChapters: ["phy-work-energy", "phy-rotation"],
    },
    {
      id: "phy-rotation",
      subject: "Physics",
      chapter: "Rotational Motion",
      class: "Class 11",
      unit: "Mechanics 1",
      yearWiseQuestionCount: {
        "2019": 9,
        "2020": 9,
        "2021": 9,
        "2022": 9,
        "2023": 9,
        "2024": 2,
        "2025": 5,
      },
      questionSolved: 52,
      totalQuestions: 52,
      status: "Completed",
      isWeakChapter: false,
      difficulty: "Hard",
      estimatedTime: 420,
      lastStudied: "2024-12-03T11:00:00Z",
      accuracy: 88,
      tags: ["angular motion", "torque", "moment of inertia", "angular momentum"],
      description: "Rotational kinematics, dynamics, moment of inertia, and angular momentum.",
      prerequisites: ["Laws of Motion", "Work Power Energy"],
      relatedChapters: ["phy-work-energy", "phy-momentum"],
    },
    {
      id: "phy-gravitation",
      subject: "Physics",
      chapter: "Gravitation",
      class: "Class 11",
      unit: "Mechanics 1",
      yearWiseQuestionCount: {
        "2019": 3,
        "2020": 4,
        "2021": 5,
        "2022": 9,
        "2023": 0,
        "2024": 6,
        "2025": 8,
      },
      questionSolved: 35,
      totalQuestions: 35,
      status: "Completed",
      isWeakChapter: false,
      difficulty: "Medium",
      estimatedTime: 240,
      lastStudied: "2024-11-25T13:30:00Z",
      accuracy: 92,
      tags: ["gravity", "orbital motion", "Kepler's laws", "gravitational field"],
      description: "Universal law of gravitation, gravitational field, orbital motion, and Kepler's laws.",
      prerequisites: ["Motion In Two Dimensions", "Laws of Motion"],
      relatedChapters: ["phy-work-energy"],
    },
    {
      id: "phy-solids",
      subject: "Physics",
      chapter: "Mechanical Properties of Solids",
      class: "Class 11",
      unit: "Mechanics 2",
      yearWiseQuestionCount: {
        "2019": 4,
        "2020": 6,
        "2021": 0,
        "2022": 2,
        "2023": 10,
        "2024": 10,
        "2025": 7,
      },
      questionSolved: 0,
      totalQuestions: 39,
      status: "Not Started",
      isWeakChapter: false,
      difficulty: "Medium",
      estimatedTime: 180,
      accuracy: 0,
      tags: ["stress", "strain", "elasticity", "Young's modulus"],
      description: "Elastic behavior of solids, stress, strain, and elastic moduli.",
      prerequisites: ["Laws of Motion"],
      relatedChapters: ["phy-fluids"],
    },
    // Chemistry chapters
    {
      id: "chem-basic-concepts",
      subject: "Chemistry",
      chapter: "Some Basic Concepts of Chemistry",
      class: "Class 11",
      unit: "Physical Chemistry",
      yearWiseQuestionCount: {
        "2019": 8,
        "2020": 2,
        "2021": 8,
        "2022": 2,
        "2023": 7,
        "2024": 8,
        "2025": 4,
      },
      questionSolved: 28,
      totalQuestions: 39,
      status: "In Progress",
      isWeakChapter: false,
      difficulty: "Easy",
      estimatedTime: 150,
      lastStudied: "2024-12-04T15:45:00Z",
      accuracy: 75,
      tags: ["mole concept", "stoichiometry", "atomic mass", "molecular formula"],
      description: "Fundamental concepts including mole concept, stoichiometry, and chemical calculations.",
      prerequisites: ["Basic Mathematics"],
      relatedChapters: ["chem-atomic-structure"],
    },
    {
      id: "chem-atomic-structure",
      subject: "Chemistry",
      chapter: "Structure of Atom",
      class: "Class 11",
      unit: "Physical Chemistry",
      yearWiseQuestionCount: {
        "2019": 6,
        "2020": 3,
        "2021": 10,
        "2022": 5,
        "2023": 6,
        "2024": 6,
        "2025": 10,
      },
      questionSolved: 0,
      totalQuestions: 46,
      status: "Not Started",
      isWeakChapter: true,
      difficulty: "Hard",
      estimatedTime: 300,
      accuracy: 0,
      tags: ["atomic models", "quantum numbers", "electronic configuration", "orbitals"],
      description: "Atomic models, quantum mechanical model, electronic configuration, and periodic trends.",
      prerequisites: ["Some Basic Concepts of Chemistry"],
      relatedChapters: ["chem-periodic-table", "chem-chemical-bonding"],
    },
    // Mathematics chapters
    {
      id: "math-basics",
      subject: "Mathematics",
      chapter: "Basic of Mathematics",
      class: "Class 11",
      unit: "Miscellaneous",
      yearWiseQuestionCount: {
        "2019": 9,
        "2020": 9,
        "2021": 6,
        "2022": 5,
        "2023": 1,
        "2024": 1,
        "2025": 8,
      },
      questionSolved: 21,
      totalQuestions: 39,
      status: "In Progress",
      isWeakChapter: true,
      difficulty: "Easy",
      estimatedTime: 120,
      lastStudied: "2024-12-02T08:30:00Z",
      accuracy: 68,
      tags: ["number system", "logarithms", "functions", "inequalities"],
      description: "Fundamental mathematical concepts including number systems, functions, and basic operations.",
      prerequisites: [],
      relatedChapters: ["math-quadratic"],
    },
    {
      id: "math-quadratic",
      subject: "Mathematics",
      chapter: "Quadratic Equation",
      class: "Class 11",
      unit: "Algebra",
      yearWiseQuestionCount: {
        "2019": 1,
        "2020": 6,
        "2021": 1,
        "2022": 1,
        "2023": 9,
        "2024": 1,
        "2025": 1,
      },
      questionSolved: 0,
      totalQuestions: 20,
      status: "Not Started",
      isWeakChapter: false,
      difficulty: "Medium",
      estimatedTime: 180,
      accuracy: 0,
      tags: ["quadratic formula", "discriminant", "roots", "graphs"],
      description: "Quadratic equations, their solutions, properties of roots, and graphical representation.",
      prerequisites: ["Basic of Mathematics"],
      relatedChapters: ["math-functions", "math-coordinate-geometry"],
    },
  ]
}

export async function getSubjectStats(subject: Subject, chapters: Chapter[]) {
  const subjectChapters = chapters.filter((ch) => ch.subject === subject)

  const stats = {
    totalChapters: subjectChapters.length,
    completedChapters: subjectChapters.filter((ch) => ch.status === "Completed").length,
    inProgressChapters: subjectChapters.filter((ch) => ch.status === "In Progress").length,
    notStartedChapters: subjectChapters.filter((ch) => ch.status === "Not Started").length,
    weakChapters: subjectChapters.filter((ch) => ch.isWeakChapter).length,
    totalQuestions: subjectChapters.reduce((sum, ch) => sum + ch.totalQuestions, 0),
    solvedQuestions: subjectChapters.reduce((sum, ch) => sum + ch.questionSolved, 0),
    averageAccuracy: subjectChapters
      .filter((ch) => ch.accuracy && ch.accuracy > 0)
      .reduce((sum, ch, _, arr) => sum + (ch.accuracy || 0) / arr.length, 0),
    totalTimeSpent: subjectChapters.filter((ch) => ch.lastStudied).reduce((sum, ch) => sum + ch.estimatedTime, 0),
  }

  return stats
}
